chore: add 'test' and 'audit-this-step' workflows

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -32,6 +32,51 @@ workflows:
       - yarn@0:
           inputs:
             - command: semantic-release
+  test:
+    steps:
+    - change-workdir:
+        title: Switch working dir to test / _tmp dir
+        description: |-
+          To prevent step testing issues, like referencing relative
+          files with just './some-file' in the step's code, which would
+          work for testing the step from this directory directly
+          but would break if the step is included in another `bitrise.yml`.
+        run_if: true
+        inputs:
+        - path: ./_tmp
+        - is_create_path: true
+    - path::./:
+        title: Step Test
+        is_skippable: true 
+        description: |-
+          Run Nitro with `fail_safe=true` to prevent build to fail. Next step validate NITRO_BUILD_STATUS should be 
+        run_if: true
+        inputs:
+          - fail_safe: 'yes'
+    - script@1:
+        inputs:
+          - content: |-
+              #!/usr/bin/env bash
+              set -ex
+
+              if [[ "$NITRO_BUILD_STATUS" == "failed" ]]; then
+                echo "NITRO_BUILD_STATUS is 'failed', as expected"
+                exit 0
+              else
+                echo "NITRO_BUILD_STATUS is NOT 'failed', this is NOT expected."
+                exit 1
+              fi
+
+  # ----------------------------------------------------------------
+  # --- workflows to Share this step into a Step Library
+  audit-this-step:
+    steps:
+    - script:
+        inputs:
+        - content: |-
+            #!/bin/bash
+            set -ex
+            stepman audit --step-yml ./step.yml
 trigger_map:
   - push_branch: main
     workflow: release
